language: cpp

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # newer g++ version (also pulls libstdc++)
            - g++-4.9
            - libwww-perl
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # newer g++ version (also pulls libstdc++)
            - g++-4.9
            - libwww-perl
      before_install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - libwww-perl

script:
  - make -C src minisat2-download
  - make -C src CXXFLAGS="-Wall -O2 -g -Werror -Wno-deprecated-register -pedantic -Wno-sign-compare" -j2 && make -C regression test

matrix:
  include:
    - env: NAME="CPP-LINT"
      script: DIFF=`git diff --name-only master HEAD` && if [ "$DIFF" != "" ]; then python scripts/cpplint.py $DIFF; fi
